tox.ini
Lots of runtime warning in test cases currently, will fully adapt python 3.x later.
=> Temporarily ignore runtime warning

thriftpy/protocol/compact.py
This can silence most of the deprecation warning.
=> Use array.tobytes() on python3

thriftpy/parser/parser.py
When we use thriftpy.load(path, ....) function. if the path is absulute path, after urlparse, the scheme is 'c'/'d'/'e', and the judgment here will not be matched. So this change can make the module more friendly to Windows.
=> Matching of absolute path in Windows

tests/parser-cases/constants.thrift, tests/test_parser.py, thriftpy2/parser/lexer.py, thriftpy2/parser/parser.py
[THRIFT-3393](https://jira.apache.org/jira/browse/THRIFT-3393) added i8 as an alias for byte, for consistency with the other integer types.
=> Add i8 as alias for 'byte'

thriftpy2/rpc.py
I think it's necessary for having a default timeout for `make_client`, and the `make_server` / `make_aio_server` / `make_aio_client` have the default timeout already.
=> Add default timeout for make_client

tests/parser-cases/structs.thrift, tests/test_parser.py, thriftpy2/parser/parser.py
* Added a check in the parser to convert lines with empty set constants.
* To test this followed the example of the email struct and added a metadata struct
to the email which holdes an empty set of strings. Seemed like the most logical way
to include parser bug in the existing tests.
=> Fixes #61 parse error on empty set field value

thriftpy2/server.py
`kwargs` is supported in `TThreadedServer`, so I think `TSimpleServer` should support it too.
=> Support kwargs style parameters passing in TSimpleServer

thriftpy2/rpc.py
The `timeout` param for `rpc.make_client` only works when user provides `host:port`, but ignored when user provides `unix_socket`.
This PR fixed it.
Could you bump a new version as soon as this PR is accepted? pls.
=> Enable socket_timeout on unix_socket

thriftpy2/contrib/aio/socket.py, thriftpy2/contrib/aio/transport/buffered.py
While accessing HBase via asyncio, I found that my test cases would randomly fail.  It turned out that not all of the data was being consumed by `TAsyncSocket.read()`, so I refactored it to use the `readall()` that `TAsyncBufferedTransport` uses.
I moved `readall()` into socket.py because it made sense to put it with the lower level implementation.
=> Use readall() in TAsyncSocket to ensure all data is received

thriftpy2/contrib/aio/processor.py
This PR fixes an error `TypeError: object generator can't be used in 'await' expression` when I call thriftpy2 on latest Python 3.8 with native async functions.
=> contrib.aio.processor: Fix missing asyncio.coroutine decorator

tests/test_aio.py, tests/test_protocol_compact.py, thriftpy2/contrib/aio/protocol/__init__.py, thriftpy2/contrib/aio/protocol/base.py, thriftpy2/contrib/aio/protocol/binary.py, thriftpy2/contrib/aio/protocol/compact.py, thriftpy2/contrib/aio/server.py, thriftpy2/contrib/aio/transport/__init__.py, thriftpy2/contrib/aio/transport/base.py, thriftpy2/contrib/aio/transport/buffered.py, thriftpy2/contrib/aio/transport/framed.py, thriftpy2/protocol/__init__.py, thriftpy2/protocol/base.py, thriftpy2/protocol/binary.py, thriftpy2/protocol/compact.py, thriftpy2/protocol/json.py, thriftpy2/transport/__init__.py, thriftpy2/transport/base.py, thriftpy2/transport/buffered/__init__.py, thriftpy2/transport/framed/__init__.py, thriftpy2/transport/memory/__init__.py
As promised, I'm implementing proper interfaces and cleaning up some parts of the code. I'll let you know when this is ready.:)
=> Add TAsyncProtocolBase and TAsyncTransportBase

thriftpy2/protocol/exc.py
Add `__str__` on `TProtocolException` with same behavior like `TApplicationException`.
close #104
=> Add __str__ on TProtocolException

thriftpy2/rpc.py
For using thriftpy2 client in IPv6 enviroment.
=> Support passing socket_family in make_client

MANIFEST.in
If a vendor wants to validate the thriftpy2 against his python stack this allows him to use the pypi archive instead of relying on github tags.
=> Include tests in the sdist tarball on pypi

tests/test_aio.py, thriftpy2/contrib/aio/rpc.py
The [standard `make_client()`](https://github.com/Thriftpy/thriftpy2/blob/master/thriftpy2/rpc.py#L33) uses the `timeout` argument to specify the socket timeout whereas the [asyncio `make_client()`](https://github.com/Thriftpy/thriftpy2/blob/master/thriftpy2/contrib/aio/rpc.py#L26) calls it `socket_timeout`. Since AIOHappyBase handles both, it leads to awkward dispatch issue where I have to rewrite the argument for one. 
This PR deprecates `socket_timeout` in favor of just `timeout` so that the async `make_client()` matches the standard one. I chose this and not the other way around so it would have the least impact on existing code, even though the `socket_timeout` name is more descriptive and probably better.
=> Rename socket_timeout to timeout for compatibility

tests/compatible/version_2/tracking.py, tests/test_aio.py, tests/test_tornado.py, tests/test_tracking.py, thriftpy2/contrib/aio/processor.py, thriftpy2/contrib/tracking/__init__.py, thriftpy2/tornado.py
This fixes the issue that exceptions may be dropped silently in TProcessor. The issue was introduced in https://github.com/Thriftpy/thriftpy2/pull/4.
=> Fix exception handling in TProcessor

thriftpy2/http.py, thriftpy2/protocol/cybin/cybin.pyx, thriftpy2/transport/buffered/cybuffered.pyx
**TL;DR**
This PR solves two issues:
- TCyBufferedTransport flusing the underlying transport before the message is complete
- HTTP client only supporting pure Python TBufferedTransport
-----
While developing an alternative HTTP client to the one in thriftpy2.http using HTTPX (so I can use the same GSSAPI authentication on both sync and async) I ran into the issue [described here:](https://github.com/Thriftpy/thriftpy2/blob/master/thriftpy2/http.py#L68)
>  Also, using TCyBufferedTransportFactory will let THttpClient write a broken string to server, which making server freezed in transport.readall() method.
After some debugging, I discovered that this is because TCyBufferedTransport [flushes its underlying transport when its buffer size will be exceeded by a …
=> Support Cython in HTTP and fix TCyBufferedTransport early flush issue

tests/parser-cases/issue_121.include.thrift, tests/parser-cases/issue_121.thrift, tests/test_http.py, tests/test_parser.py, thriftpy2/parser/parser.py
Not a completed work, for now just support "one level include", like including a file called "com.example.api.thrift".
On the opposite, including a file called "com.example.thrift", which also including another file "api.thrift", is not supported now.
So this PR is marked as WIP, I'll try to finish this latter.
Close #121
=> Support include files with dot in name

tests/test_http.py, thriftpy2/http.py
=> Fix HTTP_URI typo in http.py

tests/test_http.py, thriftpy2/http.py
Our thrift implementation needs to have some custom headers in the HTTP call, and since the implementation was almost there I updated the make_client function to support it
=> add support for custom headers for HTTP

tests/addressbook.thrift, tests/test_rpc.py, thriftpy2/thrift.py
Currently `TApplicationException` raised from user's codes (RPC handler) will be treated as normal Pyhthon error. But if we can send it to client, it will be convenient to use it to handle any unknown exceptions.
=> Send TApplicationException to client if raised

tests/test_http.py, thriftpy2/http.py
Bofore #148, `path` in `make_client` / `client_context` should have `/` prefix. After #148 been merged, `path` must have no `/` prefix, this will break exists codes using it, and as @dmulter said, `path` should have `/`.
In this PR, thriftpy2 will support these two usecases both, and the no `/` prefix is malformed but I think we should not break exists code again.
=> Fix the path issue caused by #148

tests/parser-cases/e_duplicate_exception.thrift, tests/parser-cases/e_duplicate_function.thrift, tests/parser-cases/e_duplicate_service.thrift, tests/parser-cases/e_duplicate_struct.thrift, tests/test_parser.py, thriftpy2/parser/parser.py
See https://github.com/Thriftpy/thriftpy2/issues/166. This is a deadbrain first draft. Consts gets a special exception because it's always types without a `__name__` attribute--I don't think this case matters for them anyway.
=> Raise an exception when duplicate names parsed

thriftpy2/contrib/aio/processor.py, thriftpy2/contrib/aio/protocol/binary.py
Some functions returns a coroutine.
`yield from` is necessary for them.
=> yield from is necessary when using coroutine in aio

tests/test_socket.py, thriftpy2/transport/socket.py
This is similar to: https://github.com/redis/redis-py/pull/1797
Currently, `TSocket.close()` won't continue to close the socket if it encounters an `OSError` on `socket.shutdown`. An `OSError` can happen on `socket.shutdown` if the server side of the connection disconnected already. Not running `socket.close` prevents garbage collection from cleaning up the socket and will use more memory than necessary (maybe even causing a leak?).
This PR puts a separate try/except around `socket.close` and `socket.shutdown` to allow the socket to be closed after a failed shutdown.
=> close TSocket socket after server disconnect

tox.ini
=> fix issue that py3.4 cannot use pytest due to latest attr dropping support.

tests/test_socket.py, thriftpy2/transport/socket.py
This is the same as this other PR that was recently merged: https://github.com/Thriftpy/thriftpy2/pull/183
But it fixes the issue in `TServerSocket` too.
=> close TServerSocket socket after server disconnect

setup.py, thriftpy2/contrib/aio/processor.py, thriftpy2/contrib/aio/socket.py
because of socket.error has deprecated, it should use OSError.errno to detect error number instead.
=> fix error under python 3.11

thriftpy2/contrib/aio/protocol/binary.py
There was a size in the existing code, 
but it seems to have been removed while applying async/await.
reference: <https://github.com/Thriftpy/thriftpy2/commit/b4abbdd14dbedbb7f057021d222d7d5b9631ecd1>
=> Fixed not specified size issue in read_val(aio)

tests/parser-cases/annotations.thrift, thriftpy2/parser/parser.py
fix: support annotations in const
=> fix: support annotations in const

.github/workflows/python-package.yml
According to https://github.com/actions/setup-python/issues/544 , the latest version of ubuntu dose not provide 3.6 python build cache, so we need pin it to ubuntu 20.04.
And the old version of pip / setuptools which support python 3.6 do not install cython before running the extension building, so we need to install it before install the thriftpy package.
=> try to fix ci

thriftpy2/transport/cybase.pyx
Since cython3 is released, the main change is the default language level bumped to 3. This caused thriftpy2's CI failed (see #219).
=> fix: compatible with cython3

pyproject.toml, setup.py
For latest setuptools, the build step has changed a lot. The main change is the build process is in an isolated environment without any pip packages.
thriftpy2's setup.py is using cython in its import stage, so the setuptools' change caused the CI failed (see: #220, except the python3.6, because it's using old version setuptools).
This commit adds the new style `pyproject.toml` and specified cython as the build dependency, so the CI can access cython in build process.
Please note that, when publish thriftpy2 to pypi server, we should using the new way described in https://setuptools.pypa.io/en/latest/userguide/quickstart.html, to build files which will be upload to pypi.
Roughly speaking, running `pip install build; python -m build` instead of `python setup.py sdist bdist_wheel`.
=> chore: add pyproject.toml and specify build dependencies

tests/test_parser.py, thriftpy2/parser/exc.py, thriftpy2/parser/parser.py
=> Fix typo word

tests/oneway.thrift, tests/test_oneway.py, thriftpy2/contrib/aio/client.py, thriftpy2/thrift.py
Based on the pr  #190 
Added a oneway test case.
=> fix the message_type of client

setup.py, thriftpy2/transport/__init__.py, thriftpy2/transport/sasl/__init__.py, thriftpy2/transport/sasl/cysasl.pyx
Adds pure Python and Cython implementation of sasl transport.
=> Add sasl transport support

tests/test_hook.py, thriftpy2/parser/__init__.py
Fixes: https://github.com/Thriftpy/thriftpy2/issues/215
I'm not sure if it's suitable to add the module directly to `sys.path`, maybe is should implement like this:
```python
for module in thrift.__thrift_meta__["includes"]:
if module not in sys.modules:
sys.modules[module.__name__+"_thrift"] = module
```
then use the import hook to make sure pickle will import the suitable module.
=> Add submodule to sys.path when loading child idl file.

tests/test_sslsocket.py, thriftpy2/_compat.py, thriftpy2/transport/_ssl.py
We will remove the python2 historical compatibility code in thriftpy2 step by step.
=> Remove historical SSL context compatibility for Python2

thriftpy2/transport/_ssl.py
Since python3.6, we can use `ssl.PROTOCOL_TLS_SERVER` and `ssl.PROTOCOL_TLS_CLIENT` to replace the deprecated `ssl.PROTOCOL_SSLv23`
=> Update ssl context and remove deprecated options

setup.py, tests/test_protocol_cybinary.py, thriftpy2/_compat.py, thriftpy2/protocol/cybin/endian_port.h
I found that it's very easy to support it on Windows. The only issue in the current master branch is that `endian_port.h` doesn't support Windows.
So I tried to use https://gist.github.com/panzi/6856583 to replace the old one. It's also used by Google's Fuchsia: https://fuchsia.googlesource.com/third_party/iperf/+/3.1.5/src/portable_endian.h
=> Support cythonized ext on Windows

tests/test_aio.py, tests/test_rpc.py, thriftpy2/contrib/aio/rpc.py, thriftpy2/rpc.py
Fix: https://github.com/Thriftpy/thriftpy2/issues/204
=> Support using ipv6 in make_client/make_server method

thriftpy2/parser/__init__.py, thriftpy2/parser/parser.py
Related to #232.  
I'm not sure if this can totally resolve the original issue, because reproducing a multi-thread bug is hard. I'd like to ship the change because it wouldn't introduce any trouble, and wait to see if there will be more multi-thread issues with the parser. Otherwise, we should introduce a big lock for all these `load` methods.
=> Move some global variables in parser into thread local

thriftpy2/parser/parser.py
=> Initialize the thread local in parser module in every thread

setup.py
This can be reverted until https://github.com/pytest-dev/pytest/issues/12263 is fixed.
=> pin pytest for it's bug

setup.py, thriftpy2/protocol/cybin/__init__.py, thriftpy2/protocol/cybin/cybin.pyx
To dismiss the deprecation warning when installing:
```
/home/xxxxx/Codes/thriftpy2/venv/lib/python3.11/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'thriftpy2.protocol.cybin' as data is deprecated, please list it in `packages`.
!!
############################
############################
Python recognizes 'thriftpy2.protocol.cybin' as an importable package,
but it is not listed in the `packages` configuration of setuptools.
'thriftpy2.protocol.cybin' has been automatically added to the distribution only
because it may contain data files, but this behavior is likely to change
in future versions of setuptools (and therefore is considered deprecated).
Please make sure that 'thriftpy2.protocol.cybin' is included as a package by using
the …
```
=> Add missing init file for cybin module

tests/test_parser.py, thriftpy2/parser/parser.py
=> Initialize parser's threadlocal in parse_fp

pyproject.toml, setup.py
Fix the error when run `python -m build`:
```
********************************************************************************
The following seems to be defined outside of `pyproject.toml`:
`optional-dependencies = {'dev': ['flake8>=2.5', 'sphinx-rtd-theme>=0.1.9', 'sphinx>=1.3', 'pytest-reraise', 'pytest<8.2.0,>=6.1.1', 'tornado<7.0,>=4.0; python_version >= "3.12"', 'tornado<6.0,>=4.0; python_version < "3.12"'], 'tornado': ['tornado<7.0,>=4.0; python_version >= "3.12"', 'tornado<6.0,>=4.0; python_version < "3.12"']}`
According to the spec (see the link below), however, setuptools CANNOT
consider this value unless `optional-dependencies` is listed as `dynamic`.
https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table
To prevent …
```
=> Move dependencies from setup.py to project.toml

pyproject.toml, setup.cfg, tox.ini
Fix: https://github.com/Thriftpy/thriftpy2/issues/299
=> fix flake8 error in local test

tests/parser-cases/foo.bar.thrift, tests/parser-cases/include.thrift, tests/parser-cases/include/included_1.thrift, tests/test_loader.py, tests/test_parser.py, thriftpy2/parser/__init__.py, thriftpy2/parser/exc.py, thriftpy2/parser/parser.py
Currently the logic of register sub module to `sys.modules` may cause conflict,
That's because of the PR https://github.com/Thriftpy/thriftpy2/pull/249 which fix https://github.com/Thriftpy/thriftpy2/issues/215
```py
def load(path,
module_name=None,
include_dirs=None,
include_dir=None,
encoding='utf-8'):
real_module = bool(module_name)
thrift = parse(path, module_name, include_dirs=include_dirs,
include_dir=include_dir, encoding=encoding)
if threadlocal.incomplete_type:
fill_incomplete_ttype(thrift, thrift)
if real_module:
sys.modules[module_name] = thrift
sub_modules = thrift.__thrift_meta__["includes"][:]
while sub_modules:
module = sub_modules.pop()
if module not in sys.modules:
sys.modules[module.__name__] = module
sub_modules.extend(module.__thrift_meta__["includes"])
return thrift …
```
=> fix: sub module conflict error

thriftpy2/contrib/aio/socket.py, thriftpy2/transport/socket.py
The latest python version changes the behavior, now if it's used with other kind of sockets (ex AF_UNIX) it raises OSError:
https://github.com/python/cpython/issues/128916
=> Use SO_REUSEPORT only for AF_INET sockets

.github/workflows/python-package.yml, thriftpy2/hook.py
- Fix flake8 lint  warning;
- ubuntu-20.04 has been removed yesterday, so upgrade to ubuntu-24.04. Python 3.6~3.7 is not supported on it, so only test these versions on Windows.
=> Make flake8 happy

tests/test_framed_transport.py, thriftpy2/server.py
PR resolves the threading daemon warnings which you can find in the [CI logs](https://github.com/Thriftpy/thriftpy2/actions/runs/14497522639/job/40668929976#step:6:268):
```python
/tmp/thriftpy2/tests/test_framed_transport.py:75: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
self.server_thread.setDaemon(True)
```
=> Resolve daemon warnings for threading methods

tests/parser-cases/service.thrift, tests/parser-cases/structs.thrift, tests/test_parser.py, thriftpy2/parser/parser.py, tox.ini
Allows `thriftpy2` to accept `Field` with optional `FieldID`.
In the Thrift IDL, [the `Field` definition](https://thrift.apache.org/docs/idl#field) looks like this:
```
[15] Field           ::=  FieldID? FieldReq? FieldType Identifier ('=' ConstValue)? XsdFieldOptions ListSeparator?
```
Of concern to this PR is the `FieldID?` portion, which indicates the field ID is optional. For instance, both of these structs are valid:
```thrift
struct Dog {
1: string name;
}
struct Dog {
string name;
}
```
In the first case the explicit id of `1` is given to the `name` field, while in the second case the omission of an `id` field is allowed. The correct behavior for fields which omit an id is to automatically assign them an id, starting with `-1` and decrementing backwards. As [the Thrift …
=> Allow for omitted `FieldID` in `Field` definitions

.github/workflows/test.yaml, pyproject.toml
Since we moved most of the metadatas from `setup.py` to `pyproject`, when using setuptools with version 59.6.0 (latest version supports Python3.6), it generates a package with name `UNKNOWN` and version `0.0.0`.
I don't know if it will works if we build the package in higher version of setuptools install it in Python3.6, but 3.6 is a very old version and has been [EOLed more than 3 years](https://devguide.python.org/versions/), so I think we can just not support it in the future and make things simple.
=> Requires Python3.7

tests/test_parser.py, thriftpy2/parser/parser.py
when parsing a grammar error thrift file will output an error stack output as follows:
```
../thriftpy2/parser/__init__.py:36: in load
thrift = parse(path, module_name, include_dirs=include_dirs,
../thriftpy2/parser/parser.py:623: in parse
parser.parse(data)
../.venv/lib/python3.12/site-packages/ply/yacc.py:333: in parse
return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
../.venv/lib/python3.12/site-packages/ply/yacc.py:1120: in parseopt_notrack
p.callable(pslice)
../thriftpy2/parser/parser.py:77: in p_include
child = parse(path, module_name=child_module_name)
../thriftpy2/parser/parser.py:623: in parse
parser.parse(data)
../.venv/lib/python3.12/site-packages/ply/yacc.py:333: in parse
return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc) …
```
=> feat: optimize error output

thriftpy2/tornado.py
Since tornado is based on asyncio too, there is no reason to continue using it instead of using asyncio directly.
=> Deprecated tornado
